<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AMDevIT.Analytics.Abstractions\AMDevIT.Analytics.Abstractions.csproj" />
    <ProjectReference Include="..\AMDevIT.Analytics.Core\AMDevIT.Analytics.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AMDevIT.Analytics.Tests.Android" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
    <PackageReference Include="Xamarin.Firebase.Analytics" Version="123.2.0.1" />
    <PackageReference Include="Xamarin.Firebase.Crashlytics" Version="120.1.0" />
  </ItemGroup>

</Project>
