<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AMDevIT.Analytics.Abstractions\AMDevIT.Analytics.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Extensions\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Xamarin.Firebase.Analytics" Version="123.2.0.1" />
    <PackageReference Include="Xamarin.Firebase.Crashlytics" Version="120.1.0" />
  </ItemGroup>

</Project>
