<Project>
  <Import Project="../Directory.Build.props" />
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <EnablePackageValidation>false</EnablePackageValidation>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" Version="4.3.3" />
  </ItemGroup>
</Project>
